### PR TITLE
Ea/faster search

### PR DESCRIPTION
**Pull request by ranjit-s**
a) This is related to EA-810 - to display search results faster.

b) It was decided in a meeting with Jane that the following implementation on the dev page is ok. 
i) In http://dev-tark.ensembl.org/, search for an entity (Eg: BMP1)
ii) In the search results page, first 10 results are displayed. 
iii) The MANE transcripts should be displayed first
iv) Then those with the recent 'To release' must be displayed 
v) If there are more than 10 results, the user can click on the button 'View all transcripts".
vi) Clicking the  'View all transcripts" button shows a "loading ..." spinner and  takes the user to the original search results page (which is slower)

c) The code changes done to display search results faster are summarised as follows:
i) the existing search boxes have been renamed to fast_search. A new [API](http://dev-tark.ensembl.org/api/transcript/newsearch/?expand=transcript_release_set%2Cgenes%2Ctranslation&identifier_field=JAG1) has also been created. 
ii) Display only 10 results of the search. If there are more than 10 results, the user can click on the button on the search results page, which will take the user to the original search page
iii)  The existing code for TranscriptSearch in transcripts/views.py orders by transcript_id. In the search results, Mane_type and to_release_dates are taken from another table. If the underlying database is MySQL, there is a known problem in Django that -  when we try to sort based on columns from another table, the sorting does not work properly. Hence, I had to load details of Mane_type and release_dates in the transcript table and change transcripts/model.py accordingly. 
iv) A one-time script has been created to load details of Mane_type and release_dates in the transcript table (please refer: https://github.com/Ensembl/tark-configs/tree/master/faster_search ).

### CODE REVIEW

**Comment by bilalebi** [comment]
Everything is functional as described, however, there is a noticable code duplication, e.g:

* `fast_search_result.html` ~= `search_result.html` except for 10 lines

* Same for `fast_search_link`/`search_link` and `fast_search_home`/`search_home` functions in `tark/tark_web/views.py`

I was wondering if there is a way to refactor the code? e.g: 

* Having a variable `fast_search_enabled` set to `True` by default -> fast search API is used

* When the user clicks on _View all X results_ `fast_search_enabled` will be set to `False` -> the _normal search_ portion of the code will be executed

**Review by bilalebi — COMMENTED** [review]
Everything is functional as described, however, there is a noticable code duplication, e.g:

* `fast_search_result.html` ~= `search_result.html` except for 10 lines

* Same for `fast_search_link`/`search_link` and `fast_search_home`/`search_home` functions in `tark/tark_web/views.py`

I was wondering if there is a way to refactor the code? e.g: 

* Having a variable `fast_search_enabled` set to `True` by default -> fast search API is used

* When the user clicks on _View all X results_ `fast_search_enabled` will be set to `False` -> the _normal search_ portion of the code will be executed

**Comment by ranjit-s** [comment]
Hi @sanjay-boddu 
Just wanted to ask your opinion as well, regarding the below review comments:
Review comments:
> Everything is functional as described, however, there is a noticable code duplication, e.g:
> 
> * `fast_search_result.html` ~= `search_result.html` except for 10 lines
> * Same for `fast_search_link`/`search_link` and `fast_search_home`/`search_home` functions in `tark/tark_web/views.py`
> 
> I was wondering if there is a way to refactor the code? e.g:
> 
> * Having a variable `fast_search_enabled` set to `True` by default -> fast search API is used
> * When the user clicks on _View all X results_ `fast_search_enabled` will be set to `False` -> the _normal search_ portion of the code will be executed

My understanding is that we need to implement below steps to incorporate above changes:
a.  In urls.py,  when we call views.search_home or views.search_link, we pass an extra option to views (as given in the Django document). This extra option will be a flag, say 'fast = True'
b. In views.py, inside classes search_home and search_link, it will render fast_search_result.html, whenever fast = True.
c. In fast_search_result.html, when the user clicks on View all X results,  we need to update fast = False, which in turn will render the original search_result.html. This will require us to pass the variable  (i.e fast) in views.py  to fast_search_result.html and then update this variable through the html.
3. If my above understanding is correct, and if it is feasible (I am checking if we can do it), I am not sure if it is good programming practice as mentioned in django document . What are your thoughts?

**Comment by ranjit-s** [comment]
Hi @bilalebi , @sanjay-boddu 
the changes discussed in previous meeting has now been implemented.
1. fast_search_enabled is an extra option passed from tark_web/urls.py to functions search_home and search_link in tark_web/views.py
2. functions  fast_search_home and fast_search_link that were present in the earlier version of tark_web/views.py of this pull request have now been deleted.
3. fast_search_result.html present in the earlier version of this pull request has now been deleted. Instead, fast_search_enabled flag has been used in search_result.html.

**Comment by ranjit-s** [comment]
Hi @bilalebi 
Apologies for the errors in the previous pull. Please find the changed code. 
Files modified: tark_web/views.py and tark_web/urls.py

**Review by bilalebi — APPROVED** [review]

**Pull request closed without merging**
